[package]
name = "user"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
case1 = {path = "../case1"}
case2 = {path = "../case2"}
case3 = {path = "../case3"}
common = {path = "../common"}